### ISSUE TITLE
mpd.js uses always "ws" also on "https" no "wss"

### ISSUE THREAD

**Issue by GlobalHunter** [bobboau/MPD.js#1]
Hi,
I'm new here at GitHub and I don't realy know if this is the right way to commit bugs, but I will try it :-).

problem: mpd.js always use "ws" on "https" too! -> Firefox stops and say insecure!
bug: line 1850

```
    if(url.substring(0, 3) == "wss"){
```

bugfix: line 1850

```
    else if(url.substring(0, 3) == "wss"){
```

this works for me.

thx for sharing you work here!

**Comment by bobboau** [comment]
Thanks for catching that :)

The typical procedure for submitting fixes on github is to use [pull requests](https://help.github.com/articles/using-pull-requests/) but I'm certainly not picky :)

I just pushed this fix
